//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int userid { get; set; }
        public string nomcomplet { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string Country { get; set; }
        public string Gender { get; set; }
        public bool isadmin { get; set; }
    }
}
