//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Visualisation
    {
        public int ReportId { get; set; }
        public string Name { get; set; }
        public string Mdxquery { get; set; }
        public int UserId { get; set; }
        public string dimcol { get; set; }
        public Nullable<int> nbcol { get; set; }
        public string dimgenename { get; set; }
        public string listemesure { get; set; }
        public string listerow { get; set; }
        public string servername { get; set; }
        public string dbname { get; set; }
    }
}
